### ISSUE TITLE
Implementing V1.1

### ISSUE THREAD

**Issue by radonnachie** [RadioAstronomySoftwareGroup/pyuvdata#1224]
I'm updating my V1.0 implementation to write out V1.1 ([repo](https://github.com/MydonSolutions/uvh5c99)).

This meant implementing the `/Header/phase_center_catalog/#` groups. 

I'm verifying my file by ingesting it with pyuvdata:
`UVData().read(args.filepath)`

I encounter an error because pyuvdata is not triggered to believe that the file is V1.1, and fails to find the datasets it expects from a V1.0 file: at [uvh5.py:329](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/69b9fa15669a7c449f65c50cdc4f5f01901085c0/pyuvdata/uvdata/uvh5.py#L329) because "phase_type" doesn't exist.

I see in the [source code](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/69b9fa15669a7c449f65c50cdc4f5f01901085c0/pyuvdata/uvdata/uvh5.py#L290-L297) that pyuvdata needs to have `self.multi_phase_center` evaluate positively in order for the file to be treated as V1.1 and I can only interpret that I have to put a boolean `multi_phase_center` dataset in the `/Header` group in order to get that to happen.

If that's the requirement, could it be revised or at least documented? Thanks folks.

```
pyuvdata in /home/radonn/.local/lib/python3.8/site-packages (2.2.10)
```

**Comment by bhazelton** [comment]
Hi @radonnachie,

Sorry about that! This is a code bug not a mistake in the documentation. I opened a PR to fix it, see #1225.

**Comment by radonnachie** [comment]
Epic! Thanks.

**Comment by radonnachie** [comment]
I now encounter an error due to a lack of [Nphase](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/main/pyuvdata/uvdata/uvh5.py#L297).

This also isn't documented anywhere. I anticipate the `len()` of the catalog dataset should suffice, but perhaps that breaks form and so Nphase should be placed alongside Npols/Ntime etc...

```
Traceback (most recent call last):
  File "../check_uvh5.py", line 9, in <module>
    uv = UVD.read(args.filepath)
  File "/home/radonn/.local/lib/python3.8/site-packages/pyuvdata/uvdata/uvdata.py", line 12704, in read
    self.read_uvh5(
  File "/home/radonn/.local/lib/python3.8/site-packages/pyuvdata/uvdata/uvdata.py", line 11714, in read_uvh5
    uvh5_obj.read_uvh5(
  File "/home/radonn/.local/lib/python3.8/site-packages/pyuvdata/uvdata/uvh5.py", line 1013, in read_uvh5
    self._read_header(
  File "/home/radonn/.local/lib/python3.8/site-packages/pyuvdata/uvdata/uvh5.py", line 297, in _read_header
    self.Nphase = int(header["Nphase"][()])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/radonn/.local/lib/python3.8/site-packages/h5py/_hl/group.py", line 328, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'Nphase' doesn't exist)"
```

**Comment by radonnachie** [comment]
Writing the length of the catalog to `Nphase` looked to solve it. No further issues AFAICT.

**Comment by radonnachie** [comment]
@bhazelton Should I open another issue in mimicry for the lack of `Nphase` in documentation? In 72 hours I'll get around to a PR for this if it's not tackled by then.

**Comment by bhazelton** [comment]
sure, that'd be great. We made a release to get the other fix out but had a problem with putting it on pypi. We're working on resolving that now.
