### ISSUE TITLE
Bug with write_ms

### ISSUE THREAD

**Issue by rlbyrne** [RadioAstronomySoftwareGroup/pyuvdata#1324]
I am attempting to convert a .uvfits file to an .ms file. I've read the .uvfits file with the `uv.read` method. `uv.check()` returns `True`. `uv.write_ms` errors with this message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/miniconda3/envs/pyuvdata/lib/python3.8/site-packages/pyuvdata/uvdata/uvdata.py", line 14423, in write_ms
    ms_obj.write_ms(
  File "/usr/local/miniconda3/envs/pyuvdata/lib/python3.8/site-packages/pyuvdata/uvdata/ms.py", line 1322, in write_ms
    self._write_ms_history(filepath)
  File "/usr/local/miniconda3/envs/pyuvdata/lib/python3.8/site-packages/pyuvdata/uvdata/ms.py", line 977, in _write_ms_history
    message.append(line_parts[3])
IndexError: list index out of range
```
I'm running the latest version of pyuvdata (2.4.0) with a developer installation.

**Comment by rlbyrne** [comment]
I found a workaround to this bug by setting `uv.history=""`. Previously, `uv.history` was:
```
'Begin measurement set history\nAPP_PARAMS;CLI_COMMAND;APPLICATION;MESSAGE;OBJECT_ID;OBSERVATION_ID;ORIG\nIN;PRIORITY;TIME\nEnd measurement set history.\n  Read/written with pyuvdata version: 2.1.2. Combined data along baselin\ne-time axis using pyuvdata. Combined data along baseline-time axis using\n pyuvdata. Combined data along baseline-time axis using pyuvdata. Combin\ned data along baseline-time axis using pyuvdata. Combined data along bas\neline-time axis using pyuvdata. Combined data along baseline-time axis u\nsing pyuvdata. Combined data along baseline-time axis using pyuvdata. Co\nmbined data along baseline-time axis using pyuvdata. Combined data along\n baseline-time axis using pyuvdata. Combined data along baseline-time ax\nis using pyuvdata. Combined data along baseline-time axis using pyuvdata\n. Combined data along baseline-time axis using pyuvdata. Combined data a\nlong baseline-time axis using pyuvdata. Combined data along baseline-tim\ne axis using pyuvdata. Combined data along baseline-time axis using pyuv\ndata. Combined data along baseline-time axis using pyuvdata. Combined da\nta along baseline-time axis using pyuvdata. Combined data along baseline\n-time axis using pyuvdata. Combined data along baseline-time axis using\npyuvdata. Combined data along baseline-time axis using pyuvdata. Combine\nd data along baseline-time axis using pyuvdata. Combined data along base\nline-time axis using pyuvdata. Combined data along baseline-time axis us\ning pyuvdata. Combined data along baseline-time axis using pyuvdata. Com\nbined data along baseline-time axis using pyuvdata. Combined data along\nbaseline-time axis using pyuvdata. Combined data along baseline-time axi\ns using pyuvdata. Combined data along baseline-time axis using pyuvdata.\n Combined data along baseline-time axis using pyuvdata.\nFlagged with pyuvdata.utils.apply_uvflags.  Downselected to specific tim\nes using pyuvdata.\n  Read/written with pyuvdata version: 2.3.2.\nCalibrated with pyuvdata.utils.uvcalibrate.'
```

**Comment by kartographer** [comment]
@rlbyrne -- I think I see the issue, looks like it might the result of a bug in a much older version of the `read_ms` function. I think I ought to be able to put together a work-around that doesn't require you obliterating your history.

**Comment by rlbyrne** [comment]
Thank you, @kartographer!
