### ISSUE TITLE
UVFlag.to_baseline() function param check is perhaps overly strict

### ISSUE THREAD

**Issue by lisaleemcb** [RadioAstronomySoftwareGroup/pyuvdata#1396]
Running into an issue where when trying to apply flags from a UVFlag file to a UVData file, if the antenna params are not in the same order, the consistency check will fail.  The check happens here:

https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/416ea5aa673ace96f11d25af935e3068f5ea123e/pyuvdata/uvflag/uvflag.py#L1703

and affects`antenna_names`,  `antenna_numbers`, and `antenna_positions`. If these params are both sorted before the comparison, then the check succeeds. So both objects have the same antennas, they are just not ordered the same. Is it possible to soften the param check, or does the ordering of these parameters matter for the code?

Example traceback copied below:
```
Traceback (most recent call last):
  File "/lustre/aoc/projects/hera/heramgr/anaconda3/envs/hera3dev/bin/xrfi_run.py", line 14, in <module>
    xrfi.xrfi_run(args.ocalfits_files,
  File "/lustre/aoc/projects/hera/H4C/h4c_software/hera_qm/hera_qm/xrfi.py", line 2410, in xrfi_run
    _run_all_filters(False, 
  File "/lustre/aoc/projects/hera/H4C/h4c_software/hera_qm/hera_qm/xrfi.py", line 2332, in _run_all_filters
    xrfi_run_step(uv=vdict['uv_v'], uv_files=model_files, alg=alg,  dtype='uvdata', correlations='both', metrics=metrics, flags=flags, uvf_apriori=vdict[start_flag_name],
  File "/lustre/aoc/projects/hera/H4C/h4c_software/hera_qm/hera_qm/xrfi.py", line 1949, in xrfi_run_step
    flag_apply(uvf_apriori, uv, keep_existing=True, run_check=run_check, run_check_acceptability=run_check_acceptability, force_pol=True)
  File "/lustre/aoc/projects/hera/H4C/h4c_software/hera_qm/hera_qm/xrfi.py", line 1274, in flag_apply
    uvf_i.to_baseline(uv, force_pol=force_pol, run_check=run_check,
  File "/lustre/aoc/projects/hera/heramgr/anaconda3/envs/hera3dev/lib/python3.9/site-packages/pyuvdata/uvflag/uvflag.py", line 1630, in to_baseline
    raise ValueError(
ValueError: antenna_names is not the same this object and on uv. The value on this object is ['HH0' 'HH1' 'HH2' 'HH11' 'HH12' 'HH13' 'HH14' 'HH23' 'HH24' 'HH25' 'HH26'
 'HH36' 'HH37' 'HH38' 'HH39' 'HH44' 'HH45' 'HH46' 'HH50' 'HH51' 'HH52'
 'HH53' 'HH58' 'HH59' 'HH65' 'HH66' 'HH67' 'HH68' 'HH73' 'HH75' 'HH81'
 'HH82' 'HH83' 'HH84' 'HH85' 'HH86' 'HH87' 'HH88' 'HH89' 'HH90' 'HH91'
 'HH92' 'HH93' 'HH94' 'HH98' 'HH99' 'HH100' 'HH101' 'HH102' 'HH103'
 'HH104' 'HH105' 'HH107' 'HH108' 'HH109' 'HH110' 'HH111' 'HH112' 'HH116'
 'HH117' 'HH118' 'HH119' 'HH120' 'HH121' 'HH122' 'HH123' 'HH124' 'HH127'
 'HH128' 'HH129' 'HH130' 'HH135' 'HH136' 'HH137' 'HH138' 'HH140' 'HH141'
 'HH142' 'HH143' 'HH144' 'HH145' 'HH155' 'HH156' 'HH157' 'HH158' 'HH160'
 'HH161' 'HH162' 'HH163' 'HH164' 'HH165' 'HH166' 'HH176' 'HH177' 'HH178'
 'HH179' 'HH180' 'HH181' 'HH182' 'HH183' 'HH184' 'HH185' 'HH186' 'HH187']; the value on uv is ['HH130', 'HH135', 'HH110', 'HH129', 'HH142', 'HH123', 'HH66', 'HH143', 'HH50', 'HH82', 'HH83', 'HH98', 'HH127', 'HH128', 'HH88', 'HH180', 'HH73', 'HH144', 'HH161', 'HH181', 'HH176', 'HH162', 'HH58', 'HH182', 'HH89', 'HH177', 'HH163', 'HH183', 'HH90', 'HH164', 'HH91', 'HH165', 'HH178', 'HH179', 'HH184', 'HH45', 'HH81', 'HH185', 'HH46', 'HH186', 'HH59', 'HH116', 'HH44', 'HH109', 'HH93', 'HH75', 'HH94', 'HH92', 'HH155', 'HH107', 'HH108', 'HH145', 'HH156', 'HH157', 'HH158', 'HH187', 'HH121', 'HH0', 'HH1', 'HH11', 'HH12', 'HH13', 'HH14', 'HH2', 'HH23', 'HH24', 'HH25', 'HH26', 'HH36', 'HH37', 'HH38', 'HH39', 'HH51', 'HH52', 'HH53', 'HH67', 'HH68', 'HH84', 'HH85', 'HH86', 'HH87', 'HH124', 'HH166', 'HH141', 'HH111', 'HH112', 'HH120', 'HH122', 'HH65', 'HH136', 'HH137', 'HH138', 'HH140', 'HH99', 'HH100', 'HH101', 'HH102', 'HH103', 'HH104', 'HH105', 'HH117', 'HH118', 'HH119', 'HH160'].

```

**Comment by bhazelton** [comment]
@lisaleemcb I have what I think is a fix in #1397, can you verify that it works for you?
