### ISSUE TITLE
Bug with write_ms

### ISSUE THREAD

**Issue by astrokatross** [RadioAstronomySoftwareGroup/pyuvdata#1411]
I'm attempting to apply some RFI flags and can read in an ms and apply the flags using `uvutils.apply_uvflag(uvd,uvf)` but then `write_ms` fails with following message: 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/pyuvdata/uvdata/uvdata.py", line 12714, in write_ms
    ms_obj.write_ms(
  File "/usr/local/lib/python3.8/dist-packages/pyuvdata/uvdata/ms.py", line 1346, in write_ms
    self._write_ms_source(filepath)
  File "/usr/local/lib/python3.8/dist-packages/pyuvdata/uvdata/ms.py", line 510, in _write_ms_source
    source_desc = tables.complete_ms_desc("SOURCE")
AttributeError: module 'casacore.tables' has no attribute 'complete_ms_desc'
```

**Comment by kartographer** [comment]
Hi @astrokatross! It looks like you might have an out-of-date version of `python-casacore`, since looking through their docs that method was added in v3.3.0 (and pyuvdata requires v3.3.1 currently, though we're going to bump to v3.5.0 in the near future). Can you check which version you have installed?

**Comment by astrokatross** [comment]
Ah @kartographer you're right. Thank you so much! I was using an outdated version inside a container and didn't realise. 

Thank you, it's all working now!
