### ISSUE TITLE
Include gdbm and bsdbb into dependencies

### ISSUE THREAD

**Issue by KentJames** [RadioAstronomySoftwareGroup/pyuvdata#475]
Without these astropy won't be able to download reference times to calculate LST's, this causes a crash, as below:

WARNING: failed to download http://maia.usno.navy.mil/ser7/finals2000A.all, using local IERS-B: No module named gdbm [astropy.utils.iers.iers]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jameskent/miniconda2/lib/python2.7/site-packages/pyuvdata/uvdata.py", line 1856, in read_miriad
    polarizations=polarizations, time_range=time_range)
  File "/Users/jameskent/miniconda2/lib/python2.7/site-packages/pyuvdata/miriad.py", line 381, in read_miriad
    self.set_lsts_from_time_array()
  File "/Users/jameskent/miniconda2/lib/python2.7/site-packages/pyuvdata/uvdata.py", line 532, in set_lsts_from_time_array
    self.lst_array = uvutils.get_lst_for_time(self.time_array, latitude, longitude, altitude)
  File "/Users/jameskent/miniconda2/lib/python2.7/site-packages/pyuvdata/utils.py", line 459, in get_lst_for_time
    jd, jd_array, atol=1e-6, rtol=1e-12))] = t.sidereal_time('apparent').radian
  File "/Users/jameskent/miniconda2/lib/python2.7/site-packages/astropy/time/core.py", line 758, in sidereal_time
    gst = self._erfa_sidereal_time(available_models[model.upper()])
  File "/Users/jameskent/miniconda2/lib/python2.7/site-packages/astropy/time/core.py", line 774, in _erfa_sidereal_time
    for jd_part in ('jd1', 'jd2')]
  File "/Users/jameskent/miniconda2/lib/python2.7/site-packages/astropy/time/core.py", line 1125, in __getattr__
    tm._set_scale(attr)
  File "/Users/jameskent/miniconda2/lib/python2.7/site-packages/astropy/time/core.py", line 496, in _set_scale
    args.append(get_dt(jd1, jd2))
  File "/Users/jameskent/miniconda2/lib/python2.7/site-packages/astropy/time/core.py", line 1247, in _get_delta_ut1_utc
    delta = iers_table.ut1_utc(jd1, jd2)
  File "/Users/jameskent/miniconda2/lib/python2.7/site-packages/astropy/utils/iers/iers.py", line 229, in ut1_utc
    self.ut1_utc_source if return_status else None)
  File "/Users/jameskent/miniconda2/lib/python2.7/site-packages/astropy/utils/iers/iers.py", line 327, in _interpolate
    self._check_interpolate_indices(i1, i, np.max(mjd))
  File "/Users/jameskent/miniconda2/lib/python2.7/site-packages/astropy/utils/iers/iers.py", line 270, in _check_interpolate_indices
    raise IERSRangeError('(some) times are outside of range covered '
astropy.utils.iers.iers.IERSRangeError: (some) times are outside of range covered by IERS table.
>>> UV.read_miriad('zen.2458140.12564.xx.HH.uv')

Tested in a clean python install, with just pyuvdata and required dependencies installed, with a HERA miriad file.

**Comment by bhazelton** [comment]
@KentJames Is this still an issue for you?
